/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {}
}

const logoMaterial = new THREE.MeshPhongMaterial({
  //color: "rgb(81,248,248)"
  color: "white",
})

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes,  } = useGLTF('models/logo2.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null} scale={0.35}>
      <mesh 
        geometry={nodes.mesh_0.geometry} 
        material={logoMaterial} 
        position={[-33.88, 19.06, 0]} 
        // @ts-ignore
        ref={e => window.el = e} 
      />
    </group>
  )
}

useGLTF.preload('models/logo2.glb')
